routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MembershipTypeController;
use App\Http\Controllers\PricingAdjustmentController;
use App\Http\Controllers\PricingOptionController;
use App\Http\Controllers\PurchasableController;
use App\Http\Controllers\VenueController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () { return view('welcome');})->name('home');

Route::group(['middleware' => config('authentication.middleware', ['web'])], __DIR__ . '/auth.php');

Route::middleware(['middleware' => 'auth', 'isAdmin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('venues', [VenueController::class, 'index'])->name('venues.index');
    Route::post('venues', [VenueController::class, 'store'])->name('venues.store');
    Route::patch('venues/{venue}', [VenueController::class, 'update'])->name('venues.update');
    Route::delete('venues/{venue}', [VenueController::class, 'destroy'])->name('venues.destroy');

    Route::get('membership-types', [MembershipTypeController::class, 'index'])->name('membership-types.index');
    Route::post('membership-types', [MembershipTypeController::class, 'store'])->name('membership-types.store');
    Route::patch('membership-types/{membershipType}', [MembershipTypeController::class, 'update'])->name('membership-types.update');
    Route::delete('membership-types/{membershipType}', [MembershipTypeController::class, 'destroy'])->name('membership-types.destroy');

    Route::post('pricing-options', [PricingOptionController::class, 'store'])->name('pricing-options.store');
    Route::patch('pricing-options/{pricingOption}', [PricingOptionController::class, 'update'])->name('pricing-options.update');
    Route::delete('pricing-options/{pricingOption}', [PricingOptionController::class, 'destroy'])->name('pricing-options.destroy');

    Route::get('purchasables', [PurchasableController::class, 'index'])->name('purchasables.index');
    Route::post('purchasables', [PurchasableController::class, 'store'])->name('purchasables.store');
    Route::patch('purchasables/{purchasable}', [PurchasableController::class, 'update'])->name('purchasables.update');
    Route::delete('purchasables/{purchasable}', [PurchasableController::class, 'destroy'])->name('purchasables.destroy');

    Route::get('pricing-adjustments', [PricingAdjustmentController::class, 'index'])->name('pricing-adjustments.index');
    Route::post('pricing-adjustments', [PricingAdjustmentController::class, 'store'])->name('pricing-adjustments.store');
    Route::patch('pricing-adjustments/{pricingAdjustment}', [PricingAdjustmentController::class, 'update'])->name('pricing-adjustments.update');
    Route::delete('pricing-adjustments/{pricingAdjustment}', [PricingAdjustmentController::class, 'destroy'])->name('pricing-adjustments.destroy');

});

resources/views/admin/dashboard.blade.php
@extends('admin.layout')
@section('content')
    <section>
        <div id="main" class="main-content flex-1 mt-12 md:mt-2 pb-24 md:pb-5">

            <div class="bg-gray-800 pt-3">
                <div class="rounded-tl-3xl bg-gradient-to-r from-blue-900 to-gray-800 p-4 shadow text-2xl text-white">
                    <h1 class="font-bold pl-2">Price List</h1>
                </div>
            </div>

            <div class="flex flex-wrap">
                <div class="w-full lg:w-full xl:w-full p-6">
                    <div class="border-b-4 border-green-600 rounded-lg shadow-xl p-5">
                        <div class="flex flex-row items-center">
                            <table class="shadow-md rounded px-8 pt-6 pb-8 mb-4">
                                <thead class="bg-gray-50 dark:bg-gray-700">
                                <tr>
                                    <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                        Venue
                                    </th>
                                    <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                        Purchasable
                                    </th>
                                    <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                        Options
                                    </th>
                                    <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                        Base price
                                    </th>
                                    <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                        Your price
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($venues as $venue)
                                    @foreach($purchasables as $purchasable)
                                        @foreach($purchasable->pricingOptions as $pricingOption)
                                            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                                <td class="py-4 px-6 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                                    {{ $venue->name }}
                                                </td>
                                                <td class="py-4 px-6 text-sm text-gray-500 whitespace-nowrap dark:text-gray-400">
                                                    {{ $purchasable->name }}
                                                </td>
                                                <td class="py-4 px-6 text-sm text-gray-500 whitespace-nowrap dark:text-gray-400">
                                                    {{ $pricingOption->name }}
                                                </td>
                                                <td class="py-4 px-6 text-sm text-gray-500 whitespace-nowrap dark:text-gray-400">
                                                    {{ $pricingOption->basePrice() }}
                                                </td>
                                                <td class="py-4 px-6 text-sm text-gray-500 whitespace-nowrap dark:text-gray-400">
                                                    {{ $pricingOption->price($venue) }}
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endforeach
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name') }}</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

    @livewireStyles

    <script src="//cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>


</head>

<body class="bg-gray-800 font-sans leading-normal tracking-normal mt-12">

<header>
    <nav aria-label="menu nav" class="bg-gray-800 pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-20 top-0">

        <div class="flex flex-wrap items-center">
            <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
                <a href="#" aria-label="Home">
                    <span class="text-xl pl-2"><i class="em em-grinning"></i></span>
                </a>
            </div>

            <div class="flex flex-1 md:w-1/3 justify-center md:justify-start text-white px-2">
                <span class="relative w-full">

                </span>
            </div>

            <div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
                <ul class="list-reset flex justify-between flex-1 md:flex-none items-center">
                    <li class="flex-1 md:flex-none md:mr-3">
                        <div class="relative inline-block">
                            <button onclick="toggleDD('myDropdown')" class="drop-button text-white py-2 px-2"> <span class="pr-2"><i class="em em-robot_face"></i></span> Hi, {{ auth()->user()->name }} <svg class="h-3 fill-current inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /></svg></button>
                            <div id="myDropdown" class="dropdownlist absolute bg-gray-800 text-white right-0 mt-3 p-3 overflow-auto z-30 invisible">
                                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout').submit();" class="p-2 hover:bg-gray-800 text-white text-sm no-underline hover:no-underline block"><i class="fas fa-sign-out-alt fa-fw"></i> Log Out</a>
                                <form action="{{ route('logout') }}" method="POST" id="logout">
                                    @csrf
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </nav>
</header>


<main>
    <div class="flex flex-col md:flex-row">
        <nav aria-label="alternative nav">
            <div class="bg-gray-800 shadow-xl h-20 fixed bottom-0 mt-12 md:relative md:h-screen z-10 w-full md:w-48 content-center">
                <div class="md:mt-12 md:w-48 md:fixed md:left-0 md:top-0 content-center md:content-start text-left justify-between">
                    <ul class="list-reset flex flex-row md:flex-col pt-3 md:py-3 px-1 md:px-2 text-center md:text-left">
                        <li class="mr-3 flex-1">
                            <a href="{{ route('admin.dashboard') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-pink-500">
                                <i class="fa fa-gbp pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 md:text-gray-200 block md:inline-block">Price List</span>
                            </a>
                        </li>
                        <li class="mr-3 flex-1">
                            <a href="{{ route('admin.venues.index') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-pink-500">
                                <i class="fas fa-home pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 md:text-gray-200 block md:inline-block">Venues</span>
                            </a>
                        </li>
                        <li class="mr-3 flex-1">
                            <a href="{{ route('admin.membership-types.index') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-purple-500">
                                <i class="fa fa-envelope pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 md:text-gray-200 block md:inline-block">Memberships</span>
                            </a>
                        </li>
                        <li class="mr-3 flex-1">
                            <a href="{{ route('admin.purchasables.index') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-orange-500">
                                <i class="fas fa-box pr-0 md:pr-3 text-blue-600"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-white md:text-white block md:inline-block">Purchasables</span>
                            </a>
                        </li>
                        <li class="mr-3 flex-1">
                            <a href="{{ route('admin.pricing-adjustments.index') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-orange-500">
                                <i class="fas fa-cogs pr-0 md:pr-3 text-blue-600"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-white md:text-white block md:inline-block">Adjustments</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="w-full">
            @yield('content')
        </section>
    </div>
</main>

<script>
    function toggleDD(myDropMenu) {
        document.getElementById(myDropMenu).classList.toggle("invisible");
    }
    function filterDD(myDropMenu, myDropMenuSearch) {
        var input, filter, ul, li, a, i;
        input = document.getElementById(myDropMenuSearch);
        filter = input.value.toUpperCase();
        div = document.getElementById(myDropMenu);
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
            if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "";
            } else {
                a[i].style.display = "none";
            }
        }
    }
    window.onclick = function(event) {
        if (!event.target.matches('.drop-button') && !event.target.matches('.drop-search')) {
            var dropdowns = document.getElementsByClassName("dropdownlist");
            for (var i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (!openDropdown.classList.contains('invisible')) {
                    openDropdown.classList.add('invisible');
                }
            }
        }
    }
</script>


@livewireScripts
</body>

</html>